### GET request to example server
POST http://localhost:8080/api/ride-intents
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjM2I1ZDcxYy01MDM3LTQ5ZTMtYTBkNS01NjQ2ZDQ5ZGRjNGMiLCJmaXJzdF9uYW1lIjoiUml5YXoiLCJsYXN0X25hbWUiOiJVZGRpbiIsImV4cCI6MTc3Mzk3ODEwNH0.STTyeaF8CWws9b21O3AVIVm2luWTgI-59xRt7qzQ64Q


{
  "direction": "HOME_TO_OFFICE",
  "sourceArea": "DLFCyberHub",
  "destinationArea": "TechPark",
  "sourceLat": 28.684128656399093,
  "sourceLng": 77.12783392108861,
  "destinationLat": 28.683167149888778,
  "destinationLng": 78.13595595970747,
  "startTime": "2027-01-31T22:14:45.000Z",
  "flexibleMinutes": 10
}